Add yml updates

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -76,6 +76,9 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y openjdk-11-jdk
 
+        # Check if Java is installed
+        java -version
+
         # Define Allure version
         ALLURE_VERSION=2.17.3
         ALLURE_URL="https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz"
@@ -88,9 +91,9 @@ jobs:
 
         # Check if the file is a valid tarball
         if [[ $(file allure.tgz) != *"gzip compressed data"* ]]; then
-        echo "Error: Downloaded file is not a valid tarball"
-        exit 1
-          fi
+          echo "Error: Downloaded file is not a valid tarball"
+          exit 1
+        fi
 
         # Extract Allure tarball
         tar -xzf allure.tgz -C /tmp
